### ISSUE TITLE
registerJsFile()

### ISSUE THREAD

**Issue by lesha20** [rmrevin/yii2-ulogin#4]
В файле Widget.php 

исправить:

    \Yii::$app
        ->getView()
        ->registerJsFile(
            '//ulogin.ru/js/ulogin.js',
            [],
            ['position' => View::POS_HEAD]
        );

на:

    \Yii::$app
        ->getView()
        ->registerJsFile(
            '//ulogin.ru/js/ulogin.js',
            ['position' => View::POS_HEAD],
            null
        );

**Comment by rmrevin** [comment]
Так вроде так и есть https://github.com/rmrevin/yii2-ulogin/blob/master/Widget.php#L74
Возможно просто не попало в последнюю версию.
Используйте 1.2.1.
