### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by webadequate** [rmrevin/yii2-ulogin#5]
В класс Widget передается конфигурационый массив с полями:

'sort' => ULogin::S_RELEVANT,
'verify' => '0',
'mobilebuttons' => '1',

Но таких полей в самом классе (Widget) нет.

На $redirect_uri приходит один token и больше ничего (поля указаны все)

**Comment by webadequate** [comment]
Получил все данные пользователя через:
$result = file_get_contents('http://ulogin.ru/token.php?token=' . $token .'&host=' . \Yii::$app->getRequest()->getServerName())

**Comment by rmrevin** [comment]
Обновил ридми, там были устаревшие названия параметров.
Также добавил `AuthAction`, который должен принимать данные от ulogin.
Прошу протестировать новую версию, т.к. я её не проверял. Сейчас нет времени.
