### ISSUE TITLE
Bad Request (#400)

### ISSUE THREAD

**Issue by sergio-s** [rmrevin/yii2-ulogin#6]
При клике на иконке соцсети перенаправляет на страницу, указанную в параметрах редиректа виджета 'redirectUri' => ['blog/index'], но выдает такую ошибку 
Bad Request (#400) Не удалось проверить переданные данные.

Скорее всего что-то с токеном . 
(Уточнение) В секции head прописан <?= Html::csrfMetaTags() ?>

**Comment by rmrevin** [comment]
@sergio-s добрый день. Проблема в том, что запрос с сервера ulogin не передает csrf токен для проверки.
Вам необходимо в контроллере, который принимает ответ от сервера ulogin [отключить проверку csrf токена](http://www.yiiframework.com/doc-2.0/yii-web-controller.html#$enableCsrfValidation-detail).

**Comment by sergio-s** [comment]
Здравствуйте.
Спасибо за оперативный ответ.
Я прописал в виджете 
`'redirectUri' => ['/site/index'],`

В контроллере SiteController по инструкции readme

```
    public function action()
    {
        return [
            // rmrevin/yii2-ulogin виджет
            'ulogin-auth' => [
                'class' => AuthAction::className(),
                'successCallback' => [$this, 'uloginSuccessCallback'],
                'errorCallback' => function($data){
                    \Yii::error($data['error']);
                },
            ]
        ];
    }

    // rmrevin/yii2-ulogin виджет
    public function uloginSuccessCallback($attributes)
    {
        //return $this->goHome();
        print_r($attributes);
    }

```
В контроллере объявил `public $enableCsrfValidation = false;`

Однако ,все равно вылетает ошибка 400

**Comment by sergio-s** [comment]
Разобрался.
 В контроллере SiteController прописал метод
```
    public function beforeAction($action)
    {
        if ($this->action->id == 'index')
        {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);

    }
```
Теперь редиректит на index без ошибки. Единственная проблема, что пришлось отключить проверку $enableCsrfValidation для первой страницы.
Возможно ли как-то по другому обойти эту проблему, чтобы редиректилось туда же, но index был с включенным $enableCsrfValidation?

**Comment by rmrevin** [comment]
@sergio-s Для этого Вам нужно просто принимать запрос на внутреннюю страницу, например - `/sign/auth/ulogin`.

**Comment by sergio-s** [comment]
У меня форма по адресу site/login 
Т.е. прописать в  не ` 'redirectUri' => ['/site/index']` ,а вот так  ` 'redirectUri' => ['site/login']`?

**Comment by rmrevin** [comment]
Вообще вот эта конструкция
```php
    public function action()
    {
        return [
            // rmrevin/yii2-ulogin виджет
            'ulogin-auth' => [
                'class' => AuthAction::className(),
                'successCallback' => [$this, 'uloginSuccessCallback'],
                'errorCallback' => function($data){
                    \Yii::error($data['error']);
                },
            ]
        ];
    }

    // rmrevin/yii2-ulogin виджет
    public function uloginSuccessCallback($attributes)
    {
        //return $this->goHome();
        print_r($attributes);
    }
```
добавляет как раз тот экшн, который должен по-умолчанию обрабатывать ответ от ulogin.
Redirect url нужно по умолчанию направлять на него.
Но Вы можете направлять куда хотите, и самостоятельно обрабатывать ответ от сервера ulogin.

**Comment by sergio-s** [comment]
Если я установлю в виджете` 'redirectUri' => ['site/ulogin-auth'],`
В контроллере SiteController
```
    public function action()
    {
        return [
            // rmrevin/yii2-ulogin виджет
            'ulogin-auth' => [
                'class' => AuthAction::className(),
                'successCallback' => [$this, 'uloginSuccessCallback'],
                'errorCallback' => function($data){
                    \Yii::error($data['error']);
                },
            ]
        ];
    }

    // rmrevin/yii2-ulogin виджет
    public function uloginSuccessCallback($attributes)
    {
        //return $this->goHome();
        print_r($attributes);
    }
```
При клике на иконку -  Not Found (#404)

**Comment by rmrevin** [comment]
`public function action()` -> `public function actions()`

**Comment by sergio-s** [comment]
Все получилось. Спасибо.
`public function actions()` - 
Просто код копи-пастил. Там в Readme  в `public function action()` у Вас тоже нужно добавить букву.

**Comment by rmrevin** [comment]
Да, эту ошибку нужно исправить, спасибо.

**Comment by xVismutx** [comment]
Но в итоге то поддержки CSRF нет?)

**Comment by rmrevin** [comment]
@xVismutx нет. Проблема на стороне сервера ulogin. Если вы его научите передавать валидный токен, тогда сможете реализовать проверку csrf на своей стороне.
Для валидации ответа Вы можете передавать любой state хеш в redirect uri (даже csrf токен) и по нему проверять, что это точно тот запрос от ulogin'a.

**Comment by yamalweb** [comment]
Иногда причина в параметре post_max_size php.ini

**Comment by chaoticsparks** [comment]
Добился того что при авторизации print_r срабатывает и выводит массив параметров. 
Я практически не знаю Yii, не понимаю как дальше обрабатывать эти значения.
На сайте уже реализована авторизация и регистрация
Не подскажите?

**Comment by rmrevin** [comment]
@chaoticsparks добрый день. Ваш вопрос не относится к ветке обсуждения, в этом случае следует создавать отдельный issue.
По Вашему вопросу - задача расширения только получить данные, которые Вы видите в print_r. Далее ваше приложение должно взять эти данные и провести авторизацию или регистрацию пользователя. То есть эту часть вы уже реализовываете самостоятельно, т.к. авторизация и регистрации практически в каждом приложение уникальны.
